language: go
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_extended_0.51_Linux-64bit.tar.gz
  - tar zvf hugo_extended_0.51_Linux-64bit.tar.gz
script:
  - ./hugo --minify --verbose
  - sudo pip install s3cmd
  - s3cmd --region=ap-southeast-2 sync --delete-removed -P --guess-mime-type --no-mime-magic -r public/ s3://mikerowecode.com/
notifications:
    email:
        on_failure: always
