url: http://mikerowecode.com
domain: mikerowecode.com
title: mikerowecode

author:
  name: Michael Rowe
  url: http://mikerowecode.com
  email: mrowe@mojain.com

markdown: kramdown
lsi: true
highlighter: rouge
permalink: /:year/:month/:title.html

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

remote_theme: chesterhow/tale
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
paginate:   10

include:
  - _pages

google_analytics: UA-6154615-1